services:
  - type: web
    name: inventory-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: inventorydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
